name: Publish Extension
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "src/**"
      - "package.json"
      - ".github/workflows/main.yaml"

env:
  ROAMJS_DEVELOPER_TOKEN: ${{ secrets.ROAMJS_DEVELOPER_TOKEN }}
  ROAMJS_EMAIL: support@roamjs.com
  ROAMJS_EXTENSION_ID: query-builder
  GITHUB_TOKEN: ${{ secrets.ROAMJS_RELEASE_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: npm install
      - uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const file = 'node_modules/@samepage/scripts/build.js';
            fs.writeFileSync(file, fs.readFileSync(file).toString().replace(/const message = /, "console.log(`https://api.github.com/repos/${process.env.GITHUB_REPOSITORY}/commits/${process.env.GITHUB_SHA}`, await axios_1.default.get(`https://api.github.com/repos/${process.env.GITHUB_REPOSITORY}/commits/${process.env.GITHUB_SHA}`, opts).then((r) => JSON.stringify(r.data)));const message = "))
      - name: build
        run: npx roamjs-scripts build --labs
      # this is for discourse graph
      - name: build
        run: npx roamjs-scripts build
      - name: publish
        run: npx roamjs-scripts publish
