name: Main - Roam To Blob Storage
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "apps/roam/**"
      - "packages/tailwind-config/**"
      - "packages/ui/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Debug environment with basic echo
        run: |
          echo "NODE_ENV=$NODE_ENV"
          echo "BLOB_READ_WRITE_TOKEN length is ${#BLOB_READ_WRITE_TOKEN}"
        env:
          NODE_ENV: production
          BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}

      - name: Run debug script
        run: npm run debug-env
        env:
          NODE_ENV: production
          BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
