name: Main - Roam To Blob Storage
on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - "apps/roam/**"
      - "packages/tailwind-config/**"
      - "packages/ui/**"

env:
  NODE_ENV: production
  BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4

        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm install
      - name: Debug environment with basic echo
        run: |
          echo "NODE_ENV=$NODE_ENV"
          echo "BLOB_READ_WRITE_TOKEN length is ${#BLOB_READ_WRITE_TOKEN}"

      - name: Build
        run: npx turbo run build --filter=roam-discourse-graph

      - name: Debug
        run: npx turbo run debug --filter=roam-discourse-graph
