name: Main - Roam To Blob Storage
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "apps/roam/**"
      - "packages/tailwind-config/**"
      - "packages/ui/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy
        run: npm run deploy
        env:
          BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
          NODE_ENV: production
