name: Main - Roam To Blob Storage
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "apps/roam/**"
      - "packages/tailwind-config/**"
      - "packages/ui/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug environment
        run: |
          echo "NODE_ENV=$NODE_ENV"
          echo "BLOB_READ_WRITE_TOKEN length is ${#BLOB_READ_WRITE_TOKEN}"
        env:
          NODE_ENV: production
          BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
